apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-delp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
      - image: shashank96nayak/platformservice
        name: platformservice